//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2018_05_18_wcf_client.Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MotorCycle", Namespace="http://schemas.datacontract.org/2004/07/_2018_05_18_wcf_host")]
    [System.SerializableAttribute()]
    public partial class MotorCycle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasSideCartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfWheelsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasSideCart {
            get {
                return this.HasSideCartField;
            }
            set {
                if ((this.HasSideCartField.Equals(value) != true)) {
                    this.HasSideCartField = value;
                    this.RaisePropertyChanged("HasSideCart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfWheels {
            get {
                return this.NumberOfWheelsField;
            }
            set {
                if ((this.NumberOfWheelsField.Equals(value) != true)) {
                    this.NumberOfWheelsField = value;
                    this.RaisePropertyChanged("NumberOfWheels");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.IFirstService")]
    public interface IFirstService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstService/GetCurrentDate", ReplyAction="http://tempuri.org/IFirstService/GetCurrentDateResponse")]
        System.DateTime GetCurrentDate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstService/GetCurrentDate", ReplyAction="http://tempuri.org/IFirstService/GetCurrentDateResponse")]
        System.Threading.Tasks.Task<System.DateTime> GetCurrentDateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstService/Multiply", ReplyAction="http://tempuri.org/IFirstService/MultiplyResponse")]
        int Multiply(int _a, int _b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstService/Multiply", ReplyAction="http://tempuri.org/IFirstService/MultiplyResponse")]
        System.Threading.Tasks.Task<int> MultiplyAsync(int _a, int _b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstService/GetMotorCycle", ReplyAction="http://tempuri.org/IFirstService/GetMotorCycleResponse")]
        _2018_05_18_wcf_client.Service.MotorCycle GetMotorCycle();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstService/GetMotorCycle", ReplyAction="http://tempuri.org/IFirstService/GetMotorCycleResponse")]
        System.Threading.Tasks.Task<_2018_05_18_wcf_client.Service.MotorCycle> GetMotorCycleAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFirstServiceChannel : _2018_05_18_wcf_client.Service.IFirstService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FirstServiceClient : System.ServiceModel.ClientBase<_2018_05_18_wcf_client.Service.IFirstService>, _2018_05_18_wcf_client.Service.IFirstService {
        
        public FirstServiceClient() {
        }
        
        public FirstServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FirstServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FirstServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FirstServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.DateTime GetCurrentDate() {
            return base.Channel.GetCurrentDate();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> GetCurrentDateAsync() {
            return base.Channel.GetCurrentDateAsync();
        }
        
        public int Multiply(int _a, int _b) {
            return base.Channel.Multiply(_a, _b);
        }
        
        public System.Threading.Tasks.Task<int> MultiplyAsync(int _a, int _b) {
            return base.Channel.MultiplyAsync(_a, _b);
        }
        
        public _2018_05_18_wcf_client.Service.MotorCycle GetMotorCycle() {
            return base.Channel.GetMotorCycle();
        }
        
        public System.Threading.Tasks.Task<_2018_05_18_wcf_client.Service.MotorCycle> GetMotorCycleAsync() {
            return base.Channel.GetMotorCycleAsync();
        }
    }
}
