<<<<<<< HEAD
-- IBZ 2. Schultag
--
-- Berater Datenbank
-------------------------------------------

-- Datenbank BeraterDB anwählen
use Berater
go

-- Foreign Key löschen
ALTER TABLE ARBEIT
	DROP CONSTRAINT IF EXISTS FK_ARBEIT_KUNDE;
ALTER TABLE ARBEIT
	DROP CONSTRAINT IF EXISTS FK_ARBEIT_BERATER;
ALTER TABLE BERATER
	DROP CONSTRAINT IF EXISTS FK_BERATER_AUFGABE;
go


IF OBJECT_ID('dbo.KUNDE','U') IS NOT NULL 
  DROP TABLE dbo.KUNDE; 


-- Alle Tabellen löschen
DROP TABLE IF EXISTS ARBEIT;
DROP TABLE IF EXISTS KUNDE;
DROP TABLE IF EXISTS BERATER;
DROP TABLE IF EXISTS AUFGABE;
go
=======
-- IBZ 2. Schultag
--
-- Berater Datenbank
-------------------------------------------

-- Datenbank BeraterDB anwählen
use Berater
go

-- Foreign Key löschen
ALTER TABLE ARBEIT
	DROP CONSTRAINT IF EXISTS FK_ARBEIT_KUNDE;
ALTER TABLE ARBEIT
	DROP CONSTRAINT IF EXISTS FK_ARBEIT_BERATER;
ALTER TABLE BERATER
	DROP CONSTRAINT IF EXISTS FK_BERATER_AUFGABE;
go


IF OBJECT_ID('dbo.KUNDE','U') IS NOT NULL 
  DROP TABLE dbo.KUNDE; 


-- Alle Tabellen löschen
DROP TABLE IF EXISTS ARBEIT;
DROP TABLE IF EXISTS KUNDE;
DROP TABLE IF EXISTS BERATER;
DROP TABLE IF EXISTS AUFGABE;
go
>>>>>>> 91c37e0a13ad9148d1d6356ee6197441ad0a42e5
