--
-- Aufgabe Fahrrad
--
-- Diese Datei löscht alle beteiligten Tabellen

DROP TABLE ABTEILUNGEN CASCADE CONSTRAINTS
/
DROP TABLE ANGESTELLTE CASCADE CONSTRAINTS
/

DROP TABLE ARTIKEL CASCADE CONSTRAINTS
/

DROP TABLE AUFTRAEGE CASCADE CONSTRAINTS
/

DROP TABLE AUFTRAGSPOSITIONEN CASCADE CONSTRAINTS
/

DROP TABLE GEH_KLASSEN CASCADE CONSTRAINTS
/

DROP TABLE KUNDEN CASCADE CONSTRAINTS
/

DROP TABLE LAGER CASCADE CONSTRAINTS
/

DROP TABLE LAGERBESTAND CASCADE CONSTRAINTS
/

DROP TABLE LIEFERANTEN CASCADE CONSTRAINTS
/

DROP TABLE LIEFERPROGRAMME CASCADE CONSTRAINTS
/

DROP TABLE  LIEFERUNGEN  CASCADE CONSTRAINTS
/

DROP TABLE  ORTE  CASCADE CONSTRAINTS
/

DROP TABLE  STRUKTUR  CASCADE CONSTRAINTS
/

DROP TABLE  TEILE  CASCADE CONSTRAINTS
/

DROP TABLE  TEILE_WERKE CASCADE CONSTRAINTS
/


DROP TABLE  WERKE CASCADE CONSTRAINTS
/

DROP SEQUENCE liefer_nr
/

DROP VIEW Rechnungen
/
